version: "3.8"

services:
  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
  birthday-wisher:
    depends_on:
      - mongodb
    build: ./birthday-wisher
    restart: unless-stopped
    ports:
      - 8080:8080
    stdin_open: true
    tty: true

volumes:
  db:
